"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
var react_1 = __importDefault(require("react"));
var semantic_ui_react_1 = require("semantic-ui-react");
var paragraph = (react_1["default"].createElement(semantic_ui_react_1.Image, { src: "https://react.semantic-ui.com/images/wireframe/short-paragraph.png" }));
exports["default"] = (function () { return (react_1["default"].createElement(semantic_ui_react_1.Item.Group, { divided: true },
    react_1["default"].createElement(semantic_ui_react_1.Item, null,
        react_1["default"].createElement(semantic_ui_react_1.Item.Image, { src: "https://react.semantic-ui.com/images/wireframe/image.png" }),
        react_1["default"].createElement(semantic_ui_react_1.Item.Content, null,
            react_1["default"].createElement(semantic_ui_react_1.Item.Header, { as: "a" }, "12 Years a Slave"),
            react_1["default"].createElement(semantic_ui_react_1.Item.Meta, null,
                react_1["default"].createElement("span", { className: "cinema" }, "Union Square 14")),
            react_1["default"].createElement(semantic_ui_react_1.Item.Description, null, paragraph),
            react_1["default"].createElement(semantic_ui_react_1.Item.Extra, null,
                react_1["default"].createElement(semantic_ui_react_1.Label, null, "IMAX"),
                react_1["default"].createElement(semantic_ui_react_1.Label, { icon: "globe", content: "Additional Languages" })))),
    react_1["default"].createElement(semantic_ui_react_1.Item, null,
        react_1["default"].createElement(semantic_ui_react_1.Item.Image, { src: "https://react.semantic-ui.com/images/wireframe/image.png" }),
        react_1["default"].createElement(semantic_ui_react_1.Item.Content, null,
            react_1["default"].createElement(semantic_ui_react_1.Item.Header, { as: "a" }, "My Neighbor Totoro"),
            react_1["default"].createElement(semantic_ui_react_1.Item.Meta, null,
                react_1["default"].createElement("span", { className: "cinema" }, "IFC Cinema")),
            react_1["default"].createElement(semantic_ui_react_1.Item.Description, null, paragraph),
            react_1["default"].createElement(semantic_ui_react_1.Item.Extra, null,
                react_1["default"].createElement(semantic_ui_react_1.Button, { primary: true, floated: "right" },
                    "Buy tickets",
                    react_1["default"].createElement(semantic_ui_react_1.Icon, { name: "right chevron" })),
                react_1["default"].createElement(semantic_ui_react_1.Label, null, "Limited")))),
    react_1["default"].createElement(semantic_ui_react_1.Item, null,
        react_1["default"].createElement(semantic_ui_react_1.Item.Image, { src: "https://react.semantic-ui.com/images/wireframe/image.png" }),
        react_1["default"].createElement(semantic_ui_react_1.Item.Content, null,
            react_1["default"].createElement(semantic_ui_react_1.Item.Header, { as: "a" }, "Watchmen"),
            react_1["default"].createElement(semantic_ui_react_1.Item.Meta, null,
                react_1["default"].createElement("span", { className: "cinema" }, "IFC")),
            react_1["default"].createElement(semantic_ui_react_1.Item.Description, null, paragraph),
            react_1["default"].createElement(semantic_ui_react_1.Item.Extra, null,
                react_1["default"].createElement(semantic_ui_react_1.Button, { primary: true, floated: "right" },
                    "Buy tickets",
                    react_1["default"].createElement(semantic_ui_react_1.Icon, { name: "right chevron" }))))),
    react_1["default"].createElement(semantic_ui_react_1.Item, null,
        react_1["default"].createElement(semantic_ui_react_1.Item.Image, { src: "https://react.semantic-ui.com/images/wireframe/image.png" }),
        react_1["default"].createElement(semantic_ui_react_1.Item.Content, null,
            react_1["default"].createElement(semantic_ui_react_1.Item.Header, { as: "a" }, "Watchmen"),
            react_1["default"].createElement(semantic_ui_react_1.Item.Meta, null,
                react_1["default"].createElement("span", { className: "cinema" }, "IFC")),
            react_1["default"].createElement(semantic_ui_react_1.Item.Description, null, paragraph),
            react_1["default"].createElement(semantic_ui_react_1.Item.Extra, null,
                react_1["default"].createElement(semantic_ui_react_1.Button, { primary: true, floated: "right" },
                    "Buy tickets",
                    react_1["default"].createElement(semantic_ui_react_1.Icon, { name: "right chevron" }))))),
    react_1["default"].createElement(semantic_ui_react_1.Item, null,
        react_1["default"].createElement(semantic_ui_react_1.Item.Image, { src: "https://react.semantic-ui.com/images/wireframe/image.png" }),
        react_1["default"].createElement(semantic_ui_react_1.Item.Content, null,
            react_1["default"].createElement(semantic_ui_react_1.Item.Header, { as: "a" }, "Watchmen"),
            react_1["default"].createElement(semantic_ui_react_1.Item.Meta, null,
                react_1["default"].createElement("span", { className: "cinema" }, "IFC")),
            react_1["default"].createElement(semantic_ui_react_1.Item.Description, null, paragraph),
            react_1["default"].createElement(semantic_ui_react_1.Item.Extra, null,
                react_1["default"].createElement(semantic_ui_react_1.Button, { primary: true, floated: "right" },
                    "Buy tickets",
                    react_1["default"].createElement(semantic_ui_react_1.Icon, { name: "right chevron" }))))))); });
